name: test-build-gcc-windows

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.compilers }}
    strategy:
      fail-fast: false
      matrix:
        compilers: [mingw-w64-x86_64-gcc]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            ${{ matrix.compilers }} 
            mingw-w64-x86_64-make 
            mingw-w64-x86_64-cmake 
            mingw-w64-x86_64-glu 
            mingw-w64-x86_64-mesa 
            mingw-w64-x86_64-libxrandr 
            mingw-w64-x86_64-libxinerama 
            mingw-w64-x86_64-libxcursor 
            mingw-w64-x86_64-libxi 
            mingw-w64-x86_64-boost

      - name: Build
        shell: msys2 {0}
        run: |
          rm -rf Release
          mkdir Release
          cd Release
          cmake -G "MinGW Makefiles" -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=Release ..
          mingw32-make

      - name: Upload Windows Release .exe
        uses: actions/upload-artifact@v4
        with:
          name: windows-release-exe
          path: Release/*.exe
